"""
Stage 4 of the pipeline: when the top two candidates are close, reorders the shortlist

Two options, RAG reranking asks the LLM to pick the best candidate given the full sentence, while the cross-encoder
scores each (query, candidate) pair together. The cross-encoder is the fallback whenever the LLM fails or is off
"""

import os
import re

import httpx
import numpy as np

from .config import OLLAMA_BASE_URL, OLLAMA_MODEL, OLLAMA_TIMEOUT, OPENROUTER_CHAT_URL, RAG_SYSTEM_PROMPT, RAG_TOP_N
from .extraction import openrouter_headers
from .logging_config import get_logger
from .resources import cross_encoder, food_index

logger = get_logger("food-nlp")


def cross_encoder_rerank(query, candidates):
    """
    Rerank a candidate list using a cross-encoder relevance model. More reliable than generative LLM reranking
    as the cross-encoder looks at both query and candidate together, eliminating potential bias.
    :param query: Food description string used as the query
    :param candidates: List of candidate dicts with a 'name' key
    :return: Index of the highest-scoring candidate
    """
    logger.debug("Cross-encoder reranking triggered")

    if len(candidates) <= 1:
        return 0

    pairs = [(query, candidate["name"]) for candidate in candidates]
    scores = cross_encoder.predict(pairs)
    return int(np.argmax(scores))


async def llm_rag_rerank(food_description, candidates, original_text=None, use_local=True):
    """
    Using local LLM to select best matching candidate
    :param use_local: Whether the output should be generated by local LLM or openrouter
    :param food_description: Users food description string
    :param candidates: Ordered list of candidate dicts (name, food_id, key_term, keywords)
    :param original_text: The entire input text for better semantic understanding
    :return: 0-based index of best candidate, or None to signal the caller should fall back
    """
    top = candidates[:RAG_TOP_N]

    # Build a context block for each candidate
    lines = []
    for i, c in enumerate(top, 1):
        entry = food_index.get(c["food_id"], {})
        kws = ", ".join(entry.get("keywords", []))
        lines.append(f"{i}. {c['name']}" + (f' ({kws})' if kws else ''))

    context_line = f'Full sentence context: "{original_text}"\n' if original_text else ""
    user_prompt = (
        f'{context_line}'
        f'Food described: "{food_description}"\n\n'
        f'Candidates:\n' + "\n".join(lines) +
        f'\n\nRespond with only the number of the best match (1-{len(top)}), or 0 if none fit.'
    )

    payload = {
        "model": OLLAMA_MODEL if use_local else os.getenv("OPENROUTER_MODEL"),
        "messages": [
            {"role": "system", "content": RAG_SYSTEM_PROMPT},
            {"role": "user",   "content": user_prompt}
        ],
        "stream": False,
        "options": {"temperature": 0, "num_predict": 8}  # we only need a single digit
    }

    try:
        if use_local:
            async with httpx.AsyncClient(timeout=OLLAMA_TIMEOUT) as client:
                resp = await client.post(f"{OLLAMA_BASE_URL}/api/chat", json=payload)
                resp.raise_for_status()
            raw = resp.json()["message"]["content"].strip()
        else:
            resp = await openrouter_rag_rerank(payload)
            raw = resp.json()["choices"][0]["message"]["content"].strip()

        idx = int(re.search(r'\d+', raw).group())
        if 1 <= idx <= len(top):
            return idx - 1 # convert to 0-based
    except Exception as exc:
        logger.warning(f"[RAG rerank] failed ({exc}), falling back to cross-encoder")
    return None # None signals fallback


async def openrouter_rag_rerank(payload):
    async with httpx.AsyncClient(timeout=OLLAMA_TIMEOUT) as client:
        resp = await client.post(OPENROUTER_CHAT_URL, headers=openrouter_headers(), json=payload)
        resp.raise_for_status()
    logger.info(f"rerank openrouter output: {resp.json()}")
    return resp
